# Generated by Django 3.1.6 on 2021-02-06 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srv', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Srv',
        ),
    ]
